phillyfan1138/option_dashboard

src/Graphs/Graphs.js
Fixes [issue 5](https://github.com/phillyfan1138/option_dashboard/issues/5)
=> fixed label issue

src/Actions/lambda.js, src/Reducers/data.js, src/utils.js
Partially fixes [issue 14](https://github.com/phillyfan1138/option_dashboard/issues/14)
=> updated reducers and api

package-lock.json, package.json, src/App.css
This fixes [issue 22](https://github.com/phillyfan1138/option_dashboard/issues/22)
=> fixed button

README.md
Hey Daniel really basic change.  I am making sure my understanding works mechanically.
=> First commit options... Test

src/App.css, src/App.js
=> layout and styles

README.md, src/App.js
=> Responsive layout

src/Actions/lambda.js, src/Actions/lambda.test.js, src/App.js, src/Graphs/Algorithms.js, src/HelperComponents/HelpButton.js, src/Reducers/data.js, src/utils.test.js
Fixes [issue 31](https://github.com/phillyfan1138/option_dashboard/issues/31) and general cleanup
=> cleanup and route base fix

src/App.js
Fixed sensitivities links and made the routes cleaner.  Hopefully final fix for [issue 31](https://github.com/phillyfan1138/option_dashboard/issues/31)
=> Route again

src/Actions/parameters.js, src/App.css, src/Forms/OptionInputs.js, src/Forms/QuantileInputs.js, src/Forms/StrikeInputs.js, src/Reducers/index.js, src/Reducers/optionParameters.js
Closes [issue 21](https://github.com/phillyfan1138/option_dashboard/issues/21)
=> cleanup and added input download

src/Graphs/Algorithms.js, src/Graphs/Graphs.js, src/utils.js
Fixes [issue 35](https://github.com/phillyfan1138/option_dashboard/issues/35)
=> fixed labels

src/Graphs/Graphs.js
Fixes [issue 41](https://github.com/phillyfan1138/option_dashboard/issues/41)
=> fixed IV Label issue

src/Forms/QuantileInputs.js, src/Forms/StrikeInputs.js
Fixes [issue 43](https://github.com/phillyfan1138/option_dashboard/issues/43)
=> removed forms and fixed function

src/App.js, src/Forms/FormHelper.js, src/Forms/QuantileInputs.js, src/Forms/StrikeInputs.js
Fixes [issue 49](https://github.com/phillyfan1138/option_dashboard/issues/49)
=> cleanup and fixed layout for strike and quantile

src/Forms/ModalInputs.js
Fixes [issue 53](https://github.com/phillyfan1138/option_dashboard/issues/53)
=> fixed form issue

src/Forms/FormHelper.js, src/Graphs/Algorithms.js, src/Graphs/Graphs.js
Fixes [issue 63](https://github.com/phillyfan1138/option_dashboard/issues/63)
=> fixed issue 63

src/Utils/utils.test.js
fixes [issue 69](https://github.com/phillyfan1138/option_dashboard/issues/69)
=> Fixed tests

src/App.js, src/Forms/FormHelper.js, src/Forms/InputCalibrator.js, src/Utils/utils.js
Fixes [issue 67](https://github.com/phillyfan1138/option_dashboard/issues/67)
=> fixed form.  I'm not ecstatic about the isNotComplete but it works

src/Graphs/Algorithms.js, src/Graphs/Algorithms.test.js, src/Reducers/data.js, src/Reducers/optionParameters.js
fixes [issue 72](https://github.com/phillyfan1138/option_dashboard/issues/72)
=> Fix market data

src/App.js, src/AsyncHoc.js, src/Cards/CardPlot.js, src/Forms/GenerateForm.js, src/Models/advanced.js, src/Utils/utils.js, src/modelSkeleton.js
fixes [issue 81](https://github.com/phillyfan1138/option_dashboard/issues/81)
=> added advanced

newModel.js, src/App.js, src/AsyncHoc.js, src/Cards/CardPlot.js, src/Models/advanced.js, src/Models/bs.js, src/Models/heston.js, src/Utils/cgmyUtils.js
Fixes [issue 83](https://github.com/phillyfan1138/option_dashboard/issues/83)
=> cleanup, improve Async generality, and fixed bounds

src/Forms/QuantileInputs.js
fixes [issue 87](https://github.com/phillyfan1138/option_dashboard/issues/87)
=> fixed quantile

package-lock.json, package.json, src/App.test.js, src/AsyncHoc.js, src/Cards/CardPlot.js, src/Forms/FormHelper.js, src/Forms/GenerateForm.js, src/Forms/InputCalibrator.js, src/Forms/QuantileInputs.js, src/Models/advanced.js, src/Utils/utils.js, src/Utils/utils.test.js
fixes [issue 90](https://github.com/phillyfan1138/option_dashboard/issues/90)
=> updated tests

src/App.test.js, src/Forms/FormHelper.js, src/Forms/GenerateForm.js, src/Utils/utils.js
fixes [issue 92](https://github.com/phillyfan1138/option_dashboard/issues/92)
=> fixed infinite loop

src/App.test.js, src/Forms/FormHelper.js
Cleaned up some extraneous console.log and added quantile tests.
=> cleanup and added quantile test
